

TeamHDissertation.pdf: reportinprogress.tex reportinprogress.bib
	pdflatex reportinprogress
	bibtex reportinprogress
	pdflatex reportinprogress
	pdflatex reportinprogress

clean:
	rm -f *.log *.aux *.toc *.out
	rm -f *.bbl *.blg
	
